info = "Baseline model with default hyperparameters"

[wandb]
turn_on = true
entity = "small_3_layer_seq_p4cnn"

[dataloader]
# Training DataLoader
train_batch_size = 8
train_num_workers = 4
train_shuffle = true
# Validation DataLoader
test_batch_size = 8
test_num_workers = 4
test_shuffle = false

# Optimizer
[optimizer]
name = "AdamW"
    [optimizer.args]
    # Parameters for AdamW optimizer
    lr = 0.001

# Learning Rate Scheduler
[lr_scheduler]
name = "CyclicLR"
    [lr_scheduler.args]
    # Parameters for CyclicLR scheduler
    base_lr=0.001
    max_lr=0.05
    step_size_up=50
    step_size_down=10

[model]
name = "SimpleP4CNNSmall"

# Training parameters
[training]
epochs = 8
r_ratio_start = 1
r_ratio_decay = 1e-5
r_ratio_min = 0.01

